version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci --prefer-offline --no-audit
      
  build:
    commands:
      - echo "Building application..."
      - npm run build
      - echo "Build completed"
      
artifacts:
  files:
    - '**/*'
  base-directory: dist
  
cache:
  paths:
    - 'node_modules/**/*'
